### ISSUE TITLE
How to query the UUID for any yara rule from the YaraHub

### ISSUE THREAD

**Issue by achilles4828** [abusech/YARAify#1]
- Say I search for a payload, 
- Get the payload hash
- Search the payload hash, get the matching Yara rule *Names*
- How to download the Yara files (considering the API needs the UUID)

I couldn't find any reference for this on the APIDocs

```
- Search for associated Yara rules w payload sha256 hash
curl -X POST -d '{ "query": "lookup_hash", "search_term": "91380be57c9e845bd46ab84a966793a76de0fc4ee7022b52316930fe4f17281c" '} https://yaraify-api.abuse.ch/api/v1/

curl -X POST -d '{ "query": "get_yara", "search_term": "Windows_Trojan_Smokeloader_3687686f" '} https://yaraify-api.abuse.ch/api/v1/
The API response doesn't yield any UUID (in any other queries)
curl -X POST -d '{ "get_yara_rule", "uuid": "8af629d9-206a-4d75-acd2-f6b21ae9b4ab21ae9b4ac" '} https://yaraify-api.abuse.ch/api/v1

```

**Comment by abusech** [comment]
Thanks for the hint. Can you check again please?

curl -X POST -d '{ "query": lookup_hash", "search_term": "0eec9f49484893acf36c1072c279dab27e4f80355a5358cbbf664b94d5944a9e" '} https://yaraify-api.abuse.ch/api/v1/

curl -X POST -d '{ "query": get_results", "task_id": "39b11833-8a98-11ed-9ee1-42010aa4000b" '} https://yaraify-api.abuse.ch/api/v1/

            {
                "rule_name": "INDICATOR_SUSPICIOUS_EXE_SandboxHookingDLL",
                "author": "ditekSHen",
                "description": "Detects binaries and memory artifcats referencing sandbox DLLs typically observed in sandbox evasion",
                "reference": null,
                "yarahub_uuid": null,
                "tlp": "WHITE"
            },
            {
                "rule_name": "win_phorpiex_a_84fc",
                "author": "Johannes Bader",
                "description": "detects unpacked Phorpiex samples",
                "reference": null,
                "yarahub_uuid": "84fc2940-d204-4d75-9f17-89cce6b1dea2", <-------------
                "tlp": "WHITE"
            },
            {
                "rule_name": "win_phorpiex_auto",
                "author": "Felix Bilstein - yara-signator at cocacoding dot com",
                "description": "Detects win.phorpiex.",
                "reference": null,
                "yarahub_uuid": null,
                "tlp": "WHITE"
            },


`yarahub_uuid` is `null` when the YARA rule does not originate from YARAhub. I've updated the corresponding API documentation accordingly.

Lookup a file hash:
https://yaraify.abuse.ch/api/#query-filehash

Lookup a task ID:
https://yaraify.abuse.ch/api/#query-taskid

**Comment by achilles4828** [comment]
Hey, thanks!

**Comment by achilles4828** [comment]
Okay, another query: 
According to documentation: 
```
You can download a specific YARA rule present on YARAhub. Please take note that the author of the YARA rule must have set the YARA rule's meta field yarahub_rule_sharing_tlp to TLP:WHITE to allow sharing of the YARA rule in public.
```

However, 

![image](https://user-images.githubusercontent.com/31269811/210555041-28a182e3-4ab4-4577-a0b6-efde55a1ed85.png)

Don't get why this failed even though TLP is marked white.

To replicate:

```
curl -X POST -d '{ "query": lookup_hash", "search_term": "1bcb3eef5c6f8554249cfb5fddc68024335825a8568816ffc8c9a6e89f27c5d03" '} https://yaraify-api.abuse.ch/api/v1/

curl -X POST -d '{ "query": "get_yara_rule", "uuid": "0b490860-bada-4615-bac5-6458c101d123" '} https://yaraify-api.abuse.ch/api/v1//

```
