### ISSUE TITLE
Self-hosted YARAify

### ISSUE THREAD

**Issue by Ais8Ooz8** [abusech/YARAify#3]
I can see a [list of tools being used](https://yaraify.abuse.ch/about), but it would be great to see a repository of Python code that interacts with these various tools and provides the the YARAify API. To run YARAify on our own resources, to modernize, to experiment.

**Comment by abusech** [comment]
https://github.com/abusech/yaraify

**Comment by Ais8Ooz8** [comment]
@abusech There is no source-code repository, only 5 HTTP requests, wrapped as Python code

**Comment by Ais8Ooz8** [comment]
My question was about a fully functional self-hosted YARAify API

**Comment by abusech** [comment]
YARAify is a platform, not a open source software.

**Comment by Ais8Ooz8** [comment]
Sorry, but your answer doesn't explain anything. You have a frontend, you have a backend. If you call it "community driven threat intelligence", why is the platform source code not available to the community? What is the reason to keep the source code closed?

**Comment by abusech** [comment]
because its about the **data**, not about the software
